# ServiceAccount do agent no spoke
# Usado pelo pod do agent para acessar a API do Kubernetes local (spoke)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basic-addon-agent-sa
  namespace: {{ .AddonInstallNamespace }}
