apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: basic-addon
spec:
  addOnMeta:
    displayName: Basic Addon
    description: "Basic addon example that logs hello world on managed clusters"
  installStrategy:
    type: Placements
    placements:
      - name: all-managed-clusters
        namespace: open-cluster-management
