apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: basic-addon
spec:
  addOnMeta:
    displayName: Basic Addon
    description: "Collects pod info from spoke and reports to hub"
