apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-managed-clusters
  namespace: open-cluster-management
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
