apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-addon-agent
  namespace: open-cluster-management-agent-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-addon-agent
  template:
    metadata:
      labels:
        app: basic-addon-agent
    spec:
      containers:
        - name: agent
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              while true; do
                echo "Hello from spoke! Time: $(date)"
                sleep 60
              done
